# This is a basic workflow to help you get started with Actions
# GitHub actions
name: CI example

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: circleci/python:3.7

  steps:
  #Step 1: obtenemos codigo fuente
  - name: Build
    run: sudo chmod -R 777 $GITHUB_WORKSPACE /github /__w/_temp
  - uses: actions/checkout@v2
  # Step 2: creamos venv e instalamos dependencias
  - name: Test
    run: |
      python3 -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
      flake8 --exclude=venv* --statistics
      pytest -v
      bandit -r saludar.py -s B311
