# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Obtenemos el codigo fuente del repositorio git      
      - uses: actions/checkout@v2
      # Step 2: Instalamos las dependencias
      - name: install dependency
        run:  |
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
      # Step 3: Ejecutamos los linter test con flake8 y unist tests con pytet
      - name: Run test
        run: |
          source venv/bin/activate
          flake8 --exclude=venv* --statistics
          pytest -v
      # Step 4: Build and push docker
      - name: Build and Push Docker
        #run: |
        #    source venv/bin/activate
                #       docker/build-push-action@v1
                #
                # with: 
                #username: ${{ secrets.DOCKER_USERNAME }}
                #password: ${{ secrets.DOCKER_PASSWORD }}
                #repository: oscarlpez/app_deploy
                #tag_with_ref: true
            #      docker build -t oscarlpez/app-tested .
            # docker push oscarlpez/app-tested
      #- name: Build and Push Docker
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: oscarlpez/app-tested
          tag_with_ref: true
          tag_with_sha: true
          tag: ${{ github.sha }}
